# Generated by Django 4.2.17 on 2025-01-07 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
